language: go

go:
  - 1.8

before_install:
  - go get github.com/constabulary/gb/...
  - go get -u github.com/golang/lint/golint

deploy:
  provider: heroku
  api_key:
    secure: "484cc4bf-bc71-4f24-92a7-4b693572c55c"
  app: startbot0
  skip_cleanup: true
